
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package com.huyth.copperpack.init;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.event.RegistryEvent;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.BlockItem;

import java.util.List;
import java.util.ArrayList;

import com.huyth.copperpack.item.YellowWoolArmorItem;
import com.huyth.copperpack.item.WoolDimensionItem;
import com.huyth.copperpack.item.WoalSwordItem;
import com.huyth.copperpack.item.WoalShovelItem;
import com.huyth.copperpack.item.WoalPickaxeItem;
import com.huyth.copperpack.item.WoalHoeItem;
import com.huyth.copperpack.item.WoalDustItem;
import com.huyth.copperpack.item.WoalAxeItem;
import com.huyth.copperpack.item.WoalArmorItem;
import com.huyth.copperpack.item.White_WoolArmorItem;
import com.huyth.copperpack.item.WhistSwordItem;
import com.huyth.copperpack.item.WhistShovelItem;
import com.huyth.copperpack.item.WhistPickaxeItem;
import com.huyth.copperpack.item.WhistIngotItem;
import com.huyth.copperpack.item.WhistHoeItem;
import com.huyth.copperpack.item.WhistAxeItem;
import com.huyth.copperpack.item.WhistArmorItem;
import com.huyth.copperpack.item.SliverSwordItem;
import com.huyth.copperpack.item.SliverShovelItem;
import com.huyth.copperpack.item.SliverPickaxeItem;
import com.huyth.copperpack.item.SliverIngotItem;
import com.huyth.copperpack.item.SliverHoeItem;
import com.huyth.copperpack.item.SliverAxeItem;
import com.huyth.copperpack.item.SliverArmorItem;
import com.huyth.copperpack.item.ScopindaSwordItem;
import com.huyth.copperpack.item.ScopindaShovelItem;
import com.huyth.copperpack.item.ScopindaPickaxeItem;
import com.huyth.copperpack.item.ScopindaItem;
import com.huyth.copperpack.item.ScopindaHoeItem;
import com.huyth.copperpack.item.ScopindaAxeItem;
import com.huyth.copperpack.item.ScopindaArmorItem;
import com.huyth.copperpack.item.RedustSwordItem;
import com.huyth.copperpack.item.RedustShovelItem;
import com.huyth.copperpack.item.RedustPickaxeItem;
import com.huyth.copperpack.item.RedustHoeItem;
import com.huyth.copperpack.item.RedustDustItem;
import com.huyth.copperpack.item.RedustAxeItem;
import com.huyth.copperpack.item.RedustArmorItem;
import com.huyth.copperpack.item.ReddySwordItem;
import com.huyth.copperpack.item.ReddyShovelItem;
import com.huyth.copperpack.item.ReddyPickaxeItem;
import com.huyth.copperpack.item.ReddyIngotItem;
import com.huyth.copperpack.item.ReddyHoeItem;
import com.huyth.copperpack.item.ReddyDimensionItem;
import com.huyth.copperpack.item.ReddyAxeItem;
import com.huyth.copperpack.item.ReddyArmorItem;
import com.huyth.copperpack.item.RedWoolArmorItem;
import com.huyth.copperpack.item.PurpleWoolArmorItem;
import com.huyth.copperpack.item.PolozoSwordItem;
import com.huyth.copperpack.item.PolozoShovelItem;
import com.huyth.copperpack.item.PolozoPickaxeItem;
import com.huyth.copperpack.item.PolozoIngotItem;
import com.huyth.copperpack.item.PolozoHoeItem;
import com.huyth.copperpack.item.PolozoAxeItem;
import com.huyth.copperpack.item.PolozoArmorItem;
import com.huyth.copperpack.item.PinkWoolArmorItem;
import com.huyth.copperpack.item.OrangeWoolArmorItem;
import com.huyth.copperpack.item.Magenta_WoolArmorItem;
import com.huyth.copperpack.item.MagentaSwordItem;
import com.huyth.copperpack.item.MagentaShovelItem;
import com.huyth.copperpack.item.MagentaPickaxeItem;
import com.huyth.copperpack.item.MagentaItem;
import com.huyth.copperpack.item.MagentaHoeItem;
import com.huyth.copperpack.item.MagentaAxeItem;
import com.huyth.copperpack.item.MagentaArmorItem;
import com.huyth.copperpack.item.LogArmorItem;
import com.huyth.copperpack.item.LimeWoolArmorItem;
import com.huyth.copperpack.item.LightGrayWoolArmorItem;
import com.huyth.copperpack.item.LightBlueWoolArmorItem;
import com.huyth.copperpack.item.LenonSwordItem;
import com.huyth.copperpack.item.LenonShovelItem;
import com.huyth.copperpack.item.LenonPickaxeItem;
import com.huyth.copperpack.item.LenonHoeItem;
import com.huyth.copperpack.item.LenonDustItem;
import com.huyth.copperpack.item.LenonAxeItem;
import com.huyth.copperpack.item.LenonArmorItem;
import com.huyth.copperpack.item.LazyItemItem;
import com.huyth.copperpack.item.IcolySwordItem;
import com.huyth.copperpack.item.IcolyShovelItem;
import com.huyth.copperpack.item.IcolyPickaxeItem;
import com.huyth.copperpack.item.IcolyItem;
import com.huyth.copperpack.item.IcolyHoeItem;
import com.huyth.copperpack.item.IcolyAxeItem;
import com.huyth.copperpack.item.IcolyArmorItem;
import com.huyth.copperpack.item.HealthyItemItem;
import com.huyth.copperpack.item.GreenWoolArmorItem;
import com.huyth.copperpack.item.GreenSwordItem;
import com.huyth.copperpack.item.GreenShovelItem;
import com.huyth.copperpack.item.GreenPickaxeItem;
import com.huyth.copperpack.item.GreenItem;
import com.huyth.copperpack.item.GreenHoeItem;
import com.huyth.copperpack.item.GreenAxeItem;
import com.huyth.copperpack.item.GreenArmorItem;
import com.huyth.copperpack.item.GreeSwordItem;
import com.huyth.copperpack.item.GreeShovelItem;
import com.huyth.copperpack.item.GreePlabItem;
import com.huyth.copperpack.item.GreePickaxeItem;
import com.huyth.copperpack.item.GreeHoeItem;
import com.huyth.copperpack.item.GreeDustItem;
import com.huyth.copperpack.item.GreeAxeItem;
import com.huyth.copperpack.item.GreeArmorItem;
import com.huyth.copperpack.item.GrayWoolArmorItem;
import com.huyth.copperpack.item.GoldySwordItem;
import com.huyth.copperpack.item.GoldyShovelItem;
import com.huyth.copperpack.item.GoldyPickaxeItem;
import com.huyth.copperpack.item.GoldyIngotItem;
import com.huyth.copperpack.item.GoldyHoeItem;
import com.huyth.copperpack.item.GoldyAxeItem;
import com.huyth.copperpack.item.GoldyArmorItem;
import com.huyth.copperpack.item.GoimSwordItem;
import com.huyth.copperpack.item.GoimShovelItem;
import com.huyth.copperpack.item.GoimPickaxeItem;
import com.huyth.copperpack.item.GoimItem;
import com.huyth.copperpack.item.GoimHoeItem;
import com.huyth.copperpack.item.GoimAxeItem;
import com.huyth.copperpack.item.GoimArmorItem;
import com.huyth.copperpack.item.GironSwordItem;
import com.huyth.copperpack.item.GironShovelItem;
import com.huyth.copperpack.item.GironPickaxeItem;
import com.huyth.copperpack.item.GironIngotItem;
import com.huyth.copperpack.item.GironHoeItem;
import com.huyth.copperpack.item.GironAxeItem;
import com.huyth.copperpack.item.GironArmorItem;
import com.huyth.copperpack.item.DusttinSwordItem;
import com.huyth.copperpack.item.DusttinShovelItem;
import com.huyth.copperpack.item.DusttinPickaxeItem;
import com.huyth.copperpack.item.DusttinHoeItem;
import com.huyth.copperpack.item.DusttinDustItem;
import com.huyth.copperpack.item.DusttinAxeItem;
import com.huyth.copperpack.item.DusttinArmorItem;
import com.huyth.copperpack.item.DiagotSwordItem;
import com.huyth.copperpack.item.DiagotShovelItem;
import com.huyth.copperpack.item.DiagotPickaxeItem;
import com.huyth.copperpack.item.DiagotIngotItem;
import com.huyth.copperpack.item.DiagotHoeItem;
import com.huyth.copperpack.item.DiagotAxeItem;
import com.huyth.copperpack.item.DiagotArmorItem;
import com.huyth.copperpack.item.CyanWoolArmorItem;
import com.huyth.copperpack.item.CoppySwordItem;
import com.huyth.copperpack.item.CoppyShovelItem;
import com.huyth.copperpack.item.CoppyPickaxeItem;
import com.huyth.copperpack.item.CoppyItem;
import com.huyth.copperpack.item.CoppyHoeItem;
import com.huyth.copperpack.item.CoppyAxeItem;
import com.huyth.copperpack.item.CoppyArmorItem;
import com.huyth.copperpack.item.CopperSwordItem;
import com.huyth.copperpack.item.CopperShovelItem;
import com.huyth.copperpack.item.CopperPickaxeItem;
import com.huyth.copperpack.item.CopperIngotItem;
import com.huyth.copperpack.item.CopperHoeItem;
import com.huyth.copperpack.item.CopperAxeItem;
import com.huyth.copperpack.item.CopperArmorItem;
import com.huyth.copperpack.item.CoadySwordItem;
import com.huyth.copperpack.item.CoadyShovelItem;
import com.huyth.copperpack.item.CoadyPickaxeItem;
import com.huyth.copperpack.item.CoadyIngotItem;
import com.huyth.copperpack.item.CoadyHoeItem;
import com.huyth.copperpack.item.CoadyAxeItem;
import com.huyth.copperpack.item.CoadyArmorItem;
import com.huyth.copperpack.item.BrownWoolArmorItem;
import com.huyth.copperpack.item.BlueWoolArmorItem;
import com.huyth.copperpack.item.BludySwordItem;
import com.huyth.copperpack.item.BludyShovelItem;
import com.huyth.copperpack.item.BludyPickaxeItem;
import com.huyth.copperpack.item.BludyIngotItem;
import com.huyth.copperpack.item.BludyHoeItem;
import com.huyth.copperpack.item.BludyAxeItem;
import com.huyth.copperpack.item.BludyArmorItem;
import com.huyth.copperpack.item.BlackySwordItem;
import com.huyth.copperpack.item.BlackyShovelItem;
import com.huyth.copperpack.item.BlackyPickaxeItem;
import com.huyth.copperpack.item.BlackyItem;
import com.huyth.copperpack.item.BlackyHoeItem;
import com.huyth.copperpack.item.BlackyAxeItem;
import com.huyth.copperpack.item.BlackyArmorItem;
import com.huyth.copperpack.item.BlackWoolArmorItem;
import com.huyth.copperpack.item.BandiSwordItem;
import com.huyth.copperpack.item.BandiShovelItem;
import com.huyth.copperpack.item.BandiPickaxeItem;
import com.huyth.copperpack.item.BandiHoeItem;
import com.huyth.copperpack.item.BandiDustItem;
import com.huyth.copperpack.item.BandiAxeItem;
import com.huyth.copperpack.item.BandiArmorItem;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD)
public class CopperpackModItems {
	private static final List<Item> REGISTRY = new ArrayList<>();
	public static final Item COPPER_INGOT = register(new CopperIngotItem());
	public static final Item COPPER_ORE = register(CopperpackModBlocks.COPPER_ORE, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item COPPER_BLOCK = register(CopperpackModBlocks.COPPER_BLOCK, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item COPPER_PICKAXE = register(new CopperPickaxeItem());
	public static final Item COPPER_AXE = register(new CopperAxeItem());
	public static final Item COPPER_SWORD = register(new CopperSwordItem());
	public static final Item COPPER_SHOVEL = register(new CopperShovelItem());
	public static final Item COPPER_HOE = register(new CopperHoeItem());
	public static final Item COPPER_ARMOR_HELMET = register(new CopperArmorItem.Helmet());
	public static final Item COPPER_ARMOR_CHESTPLATE = register(new CopperArmorItem.Chestplate());
	public static final Item COPPER_ARMOR_LEGGINGS = register(new CopperArmorItem.Leggings());
	public static final Item COPPER_ARMOR_BOOTS = register(new CopperArmorItem.Boots());
	public static final Item SLIVER_INGOT = register(new SliverIngotItem());
	public static final Item SLIVER_ORE = register(CopperpackModBlocks.SLIVER_ORE, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item SLIVER_BLOCK = register(CopperpackModBlocks.SLIVER_BLOCK, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item SLIVER_PICKAXE = register(new SliverPickaxeItem());
	public static final Item SLIVER_AXE = register(new SliverAxeItem());
	public static final Item SLIVER_SWORD = register(new SliverSwordItem());
	public static final Item SLIVER_SHOVEL = register(new SliverShovelItem());
	public static final Item SLIVER_HOE = register(new SliverHoeItem());
	public static final Item SLIVER_ARMOR_HELMET = register(new SliverArmorItem.Helmet());
	public static final Item SLIVER_ARMOR_CHESTPLATE = register(new SliverArmorItem.Chestplate());
	public static final Item SLIVER_ARMOR_LEGGINGS = register(new SliverArmorItem.Leggings());
	public static final Item SLIVER_ARMOR_BOOTS = register(new SliverArmorItem.Boots());
	public static final Item DUSTTIN_DUST = register(new DusttinDustItem());
	public static final Item DUSTTIN_ORE = register(CopperpackModBlocks.DUSTTIN_ORE, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item DUSTTIN_BLOCK = register(CopperpackModBlocks.DUSTTIN_BLOCK, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item DUSTTIN_PICKAXE = register(new DusttinPickaxeItem());
	public static final Item DUSTTIN_AXE = register(new DusttinAxeItem());
	public static final Item DUSTTIN_SWORD = register(new DusttinSwordItem());
	public static final Item DUSTTIN_SHOVEL = register(new DusttinShovelItem());
	public static final Item DUSTTIN_HOE = register(new DusttinHoeItem());
	public static final Item DUSTTIN_ARMOR_HELMET = register(new DusttinArmorItem.Helmet());
	public static final Item DUSTTIN_ARMOR_CHESTPLATE = register(new DusttinArmorItem.Chestplate());
	public static final Item DUSTTIN_ARMOR_LEGGINGS = register(new DusttinArmorItem.Leggings());
	public static final Item DUSTTIN_ARMOR_BOOTS = register(new DusttinArmorItem.Boots());
	public static final Item WHITE_WOOL_ARMOR_HELMET = register(new White_WoolArmorItem.Helmet());
	public static final Item WHITE_WOOL_ARMOR_CHESTPLATE = register(new White_WoolArmorItem.Chestplate());
	public static final Item WHITE_WOOL_ARMOR_LEGGINGS = register(new White_WoolArmorItem.Leggings());
	public static final Item WHITE_WOOL_ARMOR_BOOTS = register(new White_WoolArmorItem.Boots());
	public static final Item ORANGE_WOOL_ARMOR_HELMET = register(new OrangeWoolArmorItem.Helmet());
	public static final Item ORANGE_WOOL_ARMOR_CHESTPLATE = register(new OrangeWoolArmorItem.Chestplate());
	public static final Item ORANGE_WOOL_ARMOR_LEGGINGS = register(new OrangeWoolArmorItem.Leggings());
	public static final Item ORANGE_WOOL_ARMOR_BOOTS = register(new OrangeWoolArmorItem.Boots());
	public static final Item MAGENTA_WOOL_ARMOR_HELMET = register(new Magenta_WoolArmorItem.Helmet());
	public static final Item MAGENTA_WOOL_ARMOR_CHESTPLATE = register(new Magenta_WoolArmorItem.Chestplate());
	public static final Item MAGENTA_WOOL_ARMOR_LEGGINGS = register(new Magenta_WoolArmorItem.Leggings());
	public static final Item MAGENTA_WOOL_ARMOR_BOOTS = register(new Magenta_WoolArmorItem.Boots());
	public static final Item LIGHT_BLUE_WOOL_ARMOR_HELMET = register(new LightBlueWoolArmorItem.Helmet());
	public static final Item LIGHT_BLUE_WOOL_ARMOR_CHESTPLATE = register(new LightBlueWoolArmorItem.Chestplate());
	public static final Item LIGHT_BLUE_WOOL_ARMOR_LEGGINGS = register(new LightBlueWoolArmorItem.Leggings());
	public static final Item LIGHT_BLUE_WOOL_ARMOR_BOOTS = register(new LightBlueWoolArmorItem.Boots());
	public static final Item YELLOW_WOOL_ARMOR_HELMET = register(new YellowWoolArmorItem.Helmet());
	public static final Item YELLOW_WOOL_ARMOR_CHESTPLATE = register(new YellowWoolArmorItem.Chestplate());
	public static final Item YELLOW_WOOL_ARMOR_LEGGINGS = register(new YellowWoolArmorItem.Leggings());
	public static final Item YELLOW_WOOL_ARMOR_BOOTS = register(new YellowWoolArmorItem.Boots());
	public static final Item LIME_WOOL_ARMOR_HELMET = register(new LimeWoolArmorItem.Helmet());
	public static final Item LIME_WOOL_ARMOR_CHESTPLATE = register(new LimeWoolArmorItem.Chestplate());
	public static final Item LIME_WOOL_ARMOR_LEGGINGS = register(new LimeWoolArmorItem.Leggings());
	public static final Item LIME_WOOL_ARMOR_BOOTS = register(new LimeWoolArmorItem.Boots());
	public static final Item PINK_WOOL_ARMOR_HELMET = register(new PinkWoolArmorItem.Helmet());
	public static final Item PINK_WOOL_ARMOR_CHESTPLATE = register(new PinkWoolArmorItem.Chestplate());
	public static final Item PINK_WOOL_ARMOR_LEGGINGS = register(new PinkWoolArmorItem.Leggings());
	public static final Item PINK_WOOL_ARMOR_BOOTS = register(new PinkWoolArmorItem.Boots());
	public static final Item GRAY_WOOL_ARMOR_HELMET = register(new GrayWoolArmorItem.Helmet());
	public static final Item GRAY_WOOL_ARMOR_CHESTPLATE = register(new GrayWoolArmorItem.Chestplate());
	public static final Item GRAY_WOOL_ARMOR_LEGGINGS = register(new GrayWoolArmorItem.Leggings());
	public static final Item GRAY_WOOL_ARMOR_BOOTS = register(new GrayWoolArmorItem.Boots());
	public static final Item LIGHT_GRAY_WOOL_ARMOR_HELMET = register(new LightGrayWoolArmorItem.Helmet());
	public static final Item LIGHT_GRAY_WOOL_ARMOR_CHESTPLATE = register(new LightGrayWoolArmorItem.Chestplate());
	public static final Item LIGHT_GRAY_WOOL_ARMOR_LEGGINGS = register(new LightGrayWoolArmorItem.Leggings());
	public static final Item LIGHT_GRAY_WOOL_ARMOR_BOOTS = register(new LightGrayWoolArmorItem.Boots());
	public static final Item CYAN_WOOL_ARMOR_HELMET = register(new CyanWoolArmorItem.Helmet());
	public static final Item CYAN_WOOL_ARMOR_CHESTPLATE = register(new CyanWoolArmorItem.Chestplate());
	public static final Item CYAN_WOOL_ARMOR_LEGGINGS = register(new CyanWoolArmorItem.Leggings());
	public static final Item CYAN_WOOL_ARMOR_BOOTS = register(new CyanWoolArmorItem.Boots());
	public static final Item PURPLE_WOOL_ARMOR_HELMET = register(new PurpleWoolArmorItem.Helmet());
	public static final Item PURPLE_WOOL_ARMOR_CHESTPLATE = register(new PurpleWoolArmorItem.Chestplate());
	public static final Item PURPLE_WOOL_ARMOR_LEGGINGS = register(new PurpleWoolArmorItem.Leggings());
	public static final Item PURPLE_WOOL_ARMOR_BOOTS = register(new PurpleWoolArmorItem.Boots());
	public static final Item BLUE_WOOL_ARMOR_HELMET = register(new BlueWoolArmorItem.Helmet());
	public static final Item BLUE_WOOL_ARMOR_CHESTPLATE = register(new BlueWoolArmorItem.Chestplate());
	public static final Item BLUE_WOOL_ARMOR_LEGGINGS = register(new BlueWoolArmorItem.Leggings());
	public static final Item BLUE_WOOL_ARMOR_BOOTS = register(new BlueWoolArmorItem.Boots());
	public static final Item BROWN_WOOL_ARMOR_HELMET = register(new BrownWoolArmorItem.Helmet());
	public static final Item BROWN_WOOL_ARMOR_CHESTPLATE = register(new BrownWoolArmorItem.Chestplate());
	public static final Item BROWN_WOOL_ARMOR_LEGGINGS = register(new BrownWoolArmorItem.Leggings());
	public static final Item BROWN_WOOL_ARMOR_BOOTS = register(new BrownWoolArmorItem.Boots());
	public static final Item GREEN_WOOL_ARMOR_HELMET = register(new GreenWoolArmorItem.Helmet());
	public static final Item GREEN_WOOL_ARMOR_CHESTPLATE = register(new GreenWoolArmorItem.Chestplate());
	public static final Item GREEN_WOOL_ARMOR_LEGGINGS = register(new GreenWoolArmorItem.Leggings());
	public static final Item GREEN_WOOL_ARMOR_BOOTS = register(new GreenWoolArmorItem.Boots());
	public static final Item RED_WOOL_ARMOR_HELMET = register(new RedWoolArmorItem.Helmet());
	public static final Item RED_WOOL_ARMOR_CHESTPLATE = register(new RedWoolArmorItem.Chestplate());
	public static final Item RED_WOOL_ARMOR_LEGGINGS = register(new RedWoolArmorItem.Leggings());
	public static final Item RED_WOOL_ARMOR_BOOTS = register(new RedWoolArmorItem.Boots());
	public static final Item BLACK_WOOL_ARMOR_HELMET = register(new BlackWoolArmorItem.Helmet());
	public static final Item BLACK_WOOL_ARMOR_CHESTPLATE = register(new BlackWoolArmorItem.Chestplate());
	public static final Item BLACK_WOOL_ARMOR_LEGGINGS = register(new BlackWoolArmorItem.Leggings());
	public static final Item BLACK_WOOL_ARMOR_BOOTS = register(new BlackWoolArmorItem.Boots());
	public static final Item WOOL_DIMENSION = register(new WoolDimensionItem());
	public static final Item LOG_ARMOR_HELMET = register(new LogArmorItem.Helmet());
	public static final Item LOG_ARMOR_CHESTPLATE = register(new LogArmorItem.Chestplate());
	public static final Item LOG_ARMOR_LEGGINGS = register(new LogArmorItem.Leggings());
	public static final Item LOG_ARMOR_BOOTS = register(new LogArmorItem.Boots());
	public static final Item MAGENTA = register(new MagentaItem());
	public static final Item MAGENTA_ORE = register(CopperpackModBlocks.MAGENTA_ORE, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item MAGENTA_BLOCK = register(CopperpackModBlocks.MAGENTA_BLOCK, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item MAGENTA_PICKAXE = register(new MagentaPickaxeItem());
	public static final Item MAGENTA_AXE = register(new MagentaAxeItem());
	public static final Item MAGENTA_SWORD = register(new MagentaSwordItem());
	public static final Item MAGENTA_SHOVEL = register(new MagentaShovelItem());
	public static final Item MAGENTA_HOE = register(new MagentaHoeItem());
	public static final Item MAGENTA_ARMOR_HELMET = register(new MagentaArmorItem.Helmet());
	public static final Item MAGENTA_ARMOR_CHESTPLATE = register(new MagentaArmorItem.Chestplate());
	public static final Item MAGENTA_ARMOR_LEGGINGS = register(new MagentaArmorItem.Leggings());
	public static final Item MAGENTA_ARMOR_BOOTS = register(new MagentaArmorItem.Boots());
	public static final Item GOLDY_INGOT = register(new GoldyIngotItem());
	public static final Item GOLDY_ORE = register(CopperpackModBlocks.GOLDY_ORE, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item GOLDY_BLOCK = register(CopperpackModBlocks.GOLDY_BLOCK, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item GOLDY_PICKAXE = register(new GoldyPickaxeItem());
	public static final Item GOLDY_AXE = register(new GoldyAxeItem());
	public static final Item GOLDY_SWORD = register(new GoldySwordItem());
	public static final Item GOLDY_SHOVEL = register(new GoldyShovelItem());
	public static final Item GOLDY_HOE = register(new GoldyHoeItem());
	public static final Item GOLDY_ARMOR_HELMET = register(new GoldyArmorItem.Helmet());
	public static final Item GOLDY_ARMOR_CHESTPLATE = register(new GoldyArmorItem.Chestplate());
	public static final Item GOLDY_ARMOR_LEGGINGS = register(new GoldyArmorItem.Leggings());
	public static final Item GOLDY_ARMOR_BOOTS = register(new GoldyArmorItem.Boots());
	public static final Item BLUDY_INGOT = register(new BludyIngotItem());
	public static final Item BLUDY_ORE = register(CopperpackModBlocks.BLUDY_ORE, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item BLUDY_BLOCK = register(CopperpackModBlocks.BLUDY_BLOCK, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item BLUDY_PICKAXE = register(new BludyPickaxeItem());
	public static final Item BLUDY_AXE = register(new BludyAxeItem());
	public static final Item BLUDY_SWORD = register(new BludySwordItem());
	public static final Item BLUDY_SHOVEL = register(new BludyShovelItem());
	public static final Item BLUDY_HOE = register(new BludyHoeItem());
	public static final Item BLUDY_ARMOR_HELMET = register(new BludyArmorItem.Helmet());
	public static final Item BLUDY_ARMOR_CHESTPLATE = register(new BludyArmorItem.Chestplate());
	public static final Item BLUDY_ARMOR_LEGGINGS = register(new BludyArmorItem.Leggings());
	public static final Item BLUDY_ARMOR_BOOTS = register(new BludyArmorItem.Boots());
	public static final Item REDUST_DUST = register(new RedustDustItem());
	public static final Item REDUST_ORE = register(CopperpackModBlocks.REDUST_ORE, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item REDUST_BLOCK = register(CopperpackModBlocks.REDUST_BLOCK, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item REDUST_PICKAXE = register(new RedustPickaxeItem());
	public static final Item REDUST_AXE = register(new RedustAxeItem());
	public static final Item REDUST_SWORD = register(new RedustSwordItem());
	public static final Item REDUST_SHOVEL = register(new RedustShovelItem());
	public static final Item REDUST_HOE = register(new RedustHoeItem());
	public static final Item REDUST_ARMOR_HELMET = register(new RedustArmorItem.Helmet());
	public static final Item REDUST_ARMOR_CHESTPLATE = register(new RedustArmorItem.Chestplate());
	public static final Item REDUST_ARMOR_LEGGINGS = register(new RedustArmorItem.Leggings());
	public static final Item REDUST_ARMOR_BOOTS = register(new RedustArmorItem.Boots());
	public static final Item COPPY = register(new CoppyItem());
	public static final Item COPPY_ORE = register(CopperpackModBlocks.COPPY_ORE, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item COPPY_BLOCK = register(CopperpackModBlocks.COPPY_BLOCK, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item COPPY_PICKAXE = register(new CoppyPickaxeItem());
	public static final Item COPPY_AXE = register(new CoppyAxeItem());
	public static final Item COPPY_SWORD = register(new CoppySwordItem());
	public static final Item COPPY_SHOVEL = register(new CoppyShovelItem());
	public static final Item COPPY_HOE = register(new CoppyHoeItem());
	public static final Item COPPY_ARMOR_HELMET = register(new CoppyArmorItem.Helmet());
	public static final Item COPPY_ARMOR_CHESTPLATE = register(new CoppyArmorItem.Chestplate());
	public static final Item COPPY_ARMOR_LEGGINGS = register(new CoppyArmorItem.Leggings());
	public static final Item COPPY_ARMOR_BOOTS = register(new CoppyArmorItem.Boots());
	public static final Item DIAGOT_INGOT = register(new DiagotIngotItem());
	public static final Item DIAGOT_ORE = register(CopperpackModBlocks.DIAGOT_ORE, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item DIAGOT_BLOCK = register(CopperpackModBlocks.DIAGOT_BLOCK, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item DIAGOT_PICKAXE = register(new DiagotPickaxeItem());
	public static final Item DIAGOT_AXE = register(new DiagotAxeItem());
	public static final Item DIAGOT_SWORD = register(new DiagotSwordItem());
	public static final Item DIAGOT_SHOVEL = register(new DiagotShovelItem());
	public static final Item DIAGOT_HOE = register(new DiagotHoeItem());
	public static final Item DIAGOT_ARMOR_HELMET = register(new DiagotArmorItem.Helmet());
	public static final Item DIAGOT_ARMOR_CHESTPLATE = register(new DiagotArmorItem.Chestplate());
	public static final Item DIAGOT_ARMOR_LEGGINGS = register(new DiagotArmorItem.Leggings());
	public static final Item DIAGOT_ARMOR_BOOTS = register(new DiagotArmorItem.Boots());
	public static final Item GREEN = register(new GreenItem());
	public static final Item GREEN_ORE = register(CopperpackModBlocks.GREEN_ORE, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item GREEN_BLOCK = register(CopperpackModBlocks.GREEN_BLOCK, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item GREEN_PICKAXE = register(new GreenPickaxeItem());
	public static final Item GREEN_AXE = register(new GreenAxeItem());
	public static final Item GREEN_SWORD = register(new GreenSwordItem());
	public static final Item GREEN_SHOVEL = register(new GreenShovelItem());
	public static final Item GREEN_HOE = register(new GreenHoeItem());
	public static final Item GREEN_ARMOR_HELMET = register(new GreenArmorItem.Helmet());
	public static final Item GREEN_ARMOR_CHESTPLATE = register(new GreenArmorItem.Chestplate());
	public static final Item GREEN_ARMOR_LEGGINGS = register(new GreenArmorItem.Leggings());
	public static final Item GREEN_ARMOR_BOOTS = register(new GreenArmorItem.Boots());
	public static final Item COADY_INGOT = register(new CoadyIngotItem());
	public static final Item COADY_ORE = register(CopperpackModBlocks.COADY_ORE, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item COADY_BLOCK = register(CopperpackModBlocks.COADY_BLOCK, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item COADY_PICKAXE = register(new CoadyPickaxeItem());
	public static final Item COADY_AXE = register(new CoadyAxeItem());
	public static final Item COADY_SWORD = register(new CoadySwordItem());
	public static final Item COADY_SHOVEL = register(new CoadyShovelItem());
	public static final Item COADY_HOE = register(new CoadyHoeItem());
	public static final Item COADY_ARMOR_HELMET = register(new CoadyArmorItem.Helmet());
	public static final Item COADY_ARMOR_CHESTPLATE = register(new CoadyArmorItem.Chestplate());
	public static final Item COADY_ARMOR_LEGGINGS = register(new CoadyArmorItem.Leggings());
	public static final Item COADY_ARMOR_BOOTS = register(new CoadyArmorItem.Boots());
	public static final Item LENON_DUST = register(new LenonDustItem());
	public static final Item LENON_ORE = register(CopperpackModBlocks.LENON_ORE, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item LENON_BLOCK = register(CopperpackModBlocks.LENON_BLOCK, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item LENON_PICKAXE = register(new LenonPickaxeItem());
	public static final Item LENON_AXE = register(new LenonAxeItem());
	public static final Item LENON_SWORD = register(new LenonSwordItem());
	public static final Item LENON_SHOVEL = register(new LenonShovelItem());
	public static final Item LENON_HOE = register(new LenonHoeItem());
	public static final Item LENON_ARMOR_HELMET = register(new LenonArmorItem.Helmet());
	public static final Item LENON_ARMOR_CHESTPLATE = register(new LenonArmorItem.Chestplate());
	public static final Item LENON_ARMOR_LEGGINGS = register(new LenonArmorItem.Leggings());
	public static final Item LENON_ARMOR_BOOTS = register(new LenonArmorItem.Boots());
	public static final Item ICOLY = register(new IcolyItem());
	public static final Item ICOLY_ORE = register(CopperpackModBlocks.ICOLY_ORE, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item ICOLY_BLOCK = register(CopperpackModBlocks.ICOLY_BLOCK, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item ICOLY_PICKAXE = register(new IcolyPickaxeItem());
	public static final Item ICOLY_AXE = register(new IcolyAxeItem());
	public static final Item ICOLY_SWORD = register(new IcolySwordItem());
	public static final Item ICOLY_SHOVEL = register(new IcolyShovelItem());
	public static final Item ICOLY_HOE = register(new IcolyHoeItem());
	public static final Item ICOLY_ARMOR_HELMET = register(new IcolyArmorItem.Helmet());
	public static final Item ICOLY_ARMOR_CHESTPLATE = register(new IcolyArmorItem.Chestplate());
	public static final Item ICOLY_ARMOR_LEGGINGS = register(new IcolyArmorItem.Leggings());
	public static final Item ICOLY_ARMOR_BOOTS = register(new IcolyArmorItem.Boots());
	public static final Item GOIM = register(new GoimItem());
	public static final Item GOIM_ORE = register(CopperpackModBlocks.GOIM_ORE, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item GOIM_BLOCK = register(CopperpackModBlocks.GOIM_BLOCK, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item GOIM_PICKAXE = register(new GoimPickaxeItem());
	public static final Item GOIM_AXE = register(new GoimAxeItem());
	public static final Item GOIM_SWORD = register(new GoimSwordItem());
	public static final Item GOIM_SHOVEL = register(new GoimShovelItem());
	public static final Item GOIM_HOE = register(new GoimHoeItem());
	public static final Item GOIM_ARMOR_HELMET = register(new GoimArmorItem.Helmet());
	public static final Item GOIM_ARMOR_CHESTPLATE = register(new GoimArmorItem.Chestplate());
	public static final Item GOIM_ARMOR_LEGGINGS = register(new GoimArmorItem.Leggings());
	public static final Item GOIM_ARMOR_BOOTS = register(new GoimArmorItem.Boots());
	public static final Item REDDY_INGOT = register(new ReddyIngotItem());
	public static final Item REDDY_ORE = register(CopperpackModBlocks.REDDY_ORE, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item REDDY_BLOCK = register(CopperpackModBlocks.REDDY_BLOCK, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item REDDY_PICKAXE = register(new ReddyPickaxeItem());
	public static final Item REDDY_AXE = register(new ReddyAxeItem());
	public static final Item REDDY_SWORD = register(new ReddySwordItem());
	public static final Item REDDY_SHOVEL = register(new ReddyShovelItem());
	public static final Item REDDY_HOE = register(new ReddyHoeItem());
	public static final Item REDDY_ARMOR_HELMET = register(new ReddyArmorItem.Helmet());
	public static final Item REDDY_ARMOR_CHESTPLATE = register(new ReddyArmorItem.Chestplate());
	public static final Item REDDY_ARMOR_LEGGINGS = register(new ReddyArmorItem.Leggings());
	public static final Item REDDY_ARMOR_BOOTS = register(new ReddyArmorItem.Boots());
	public static final Item REDDY_DIMENSION = register(new ReddyDimensionItem());
	public static final Item WOAL_DUST = register(new WoalDustItem());
	public static final Item WOAL_ORE = register(CopperpackModBlocks.WOAL_ORE, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item WOAL_BLOCK = register(CopperpackModBlocks.WOAL_BLOCK, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item WOAL_PICKAXE = register(new WoalPickaxeItem());
	public static final Item WOAL_AXE = register(new WoalAxeItem());
	public static final Item WOAL_SWORD = register(new WoalSwordItem());
	public static final Item WOAL_SHOVEL = register(new WoalShovelItem());
	public static final Item WOAL_HOE = register(new WoalHoeItem());
	public static final Item WOAL_ARMOR_HELMET = register(new WoalArmorItem.Helmet());
	public static final Item WOAL_ARMOR_CHESTPLATE = register(new WoalArmorItem.Chestplate());
	public static final Item WOAL_ARMOR_LEGGINGS = register(new WoalArmorItem.Leggings());
	public static final Item WOAL_ARMOR_BOOTS = register(new WoalArmorItem.Boots());
	public static final Item BLACKY = register(new BlackyItem());
	public static final Item BLACKY_ORE = register(CopperpackModBlocks.BLACKY_ORE, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item BLACKY_BLOCK = register(CopperpackModBlocks.BLACKY_BLOCK, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item BLACKY_PICKAXE = register(new BlackyPickaxeItem());
	public static final Item BLACKY_AXE = register(new BlackyAxeItem());
	public static final Item BLACKY_SWORD = register(new BlackySwordItem());
	public static final Item BLACKY_SHOVEL = register(new BlackyShovelItem());
	public static final Item BLACKY_HOE = register(new BlackyHoeItem());
	public static final Item BLACKY_ARMOR_HELMET = register(new BlackyArmorItem.Helmet());
	public static final Item BLACKY_ARMOR_CHESTPLATE = register(new BlackyArmorItem.Chestplate());
	public static final Item BLACKY_ARMOR_LEGGINGS = register(new BlackyArmorItem.Leggings());
	public static final Item BLACKY_ARMOR_BOOTS = register(new BlackyArmorItem.Boots());
	public static final Item GREE_DA = register(CopperpackModBlocks.GREE_DA, CopperpackModTabs.TAB_COPPER_PACK_PLANTS);
	public static final Item GREE_DUST = register(new GreeDustItem());
	public static final Item GREE_PICKAXE = register(new GreePickaxeItem());
	public static final Item GREE_AXE = register(new GreeAxeItem());
	public static final Item GREE_SWORD = register(new GreeSwordItem());
	public static final Item GREE_SHOVEL = register(new GreeShovelItem());
	public static final Item GREE_HOE = register(new GreeHoeItem());
	public static final Item GREE_ARMOR_HELMET = register(new GreeArmorItem.Helmet());
	public static final Item GREE_ARMOR_CHESTPLATE = register(new GreeArmorItem.Chestplate());
	public static final Item GREE_ARMOR_LEGGINGS = register(new GreeArmorItem.Leggings());
	public static final Item GREE_ARMOR_BOOTS = register(new GreeArmorItem.Boots());
	public static final Item GREE_PLAB = register(new GreePlabItem());
	public static final Item LAZY_ITEM = register(new LazyItemItem());
	public static final Item LAZY_FLOWER = register(CopperpackModBlocks.LAZY_FLOWER, CopperpackModTabs.TAB_COPPER_PACK_PLANTS);
	public static final Item POLOZO_INGOT = register(new PolozoIngotItem());
	public static final Item POLOZO_ORE = register(CopperpackModBlocks.POLOZO_ORE, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item POLOZO_BLOCK = register(CopperpackModBlocks.POLOZO_BLOCK, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item POLOZO_PICKAXE = register(new PolozoPickaxeItem());
	public static final Item POLOZO_AXE = register(new PolozoAxeItem());
	public static final Item POLOZO_SWORD = register(new PolozoSwordItem());
	public static final Item POLOZO_SHOVEL = register(new PolozoShovelItem());
	public static final Item POLOZO_HOE = register(new PolozoHoeItem());
	public static final Item POLOZO_ARMOR_HELMET = register(new PolozoArmorItem.Helmet());
	public static final Item POLOZO_ARMOR_CHESTPLATE = register(new PolozoArmorItem.Chestplate());
	public static final Item POLOZO_ARMOR_LEGGINGS = register(new PolozoArmorItem.Leggings());
	public static final Item POLOZO_ARMOR_BOOTS = register(new PolozoArmorItem.Boots());
	public static final Item GIRON_INGOT = register(new GironIngotItem());
	public static final Item GIRON_ORE = register(CopperpackModBlocks.GIRON_ORE, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item GIRON_BLOCK = register(CopperpackModBlocks.GIRON_BLOCK, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item GIRON_PICKAXE = register(new GironPickaxeItem());
	public static final Item GIRON_AXE = register(new GironAxeItem());
	public static final Item GIRON_SWORD = register(new GironSwordItem());
	public static final Item GIRON_SHOVEL = register(new GironShovelItem());
	public static final Item GIRON_HOE = register(new GironHoeItem());
	public static final Item GIRON_ARMOR_HELMET = register(new GironArmorItem.Helmet());
	public static final Item GIRON_ARMOR_CHESTPLATE = register(new GironArmorItem.Chestplate());
	public static final Item GIRON_ARMOR_LEGGINGS = register(new GironArmorItem.Leggings());
	public static final Item GIRON_ARMOR_BOOTS = register(new GironArmorItem.Boots());
	public static final Item HEALTHY_ITEM = register(new HealthyItemItem());
	public static final Item HEALTHY_FLOWER = register(CopperpackModBlocks.HEALTHY_FLOWER, CopperpackModTabs.TAB_COPPER_PACK_PLANTS);
	public static final Item SCOPINDA = register(new ScopindaItem());
	public static final Item SCOPINDA_ORE = register(CopperpackModBlocks.SCOPINDA_ORE, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item SCOPINDA_BLOCK = register(CopperpackModBlocks.SCOPINDA_BLOCK, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item SCOPINDA_PICKAXE = register(new ScopindaPickaxeItem());
	public static final Item SCOPINDA_AXE = register(new ScopindaAxeItem());
	public static final Item SCOPINDA_SWORD = register(new ScopindaSwordItem());
	public static final Item SCOPINDA_SHOVEL = register(new ScopindaShovelItem());
	public static final Item SCOPINDA_HOE = register(new ScopindaHoeItem());
	public static final Item SCOPINDA_ARMOR_HELMET = register(new ScopindaArmorItem.Helmet());
	public static final Item SCOPINDA_ARMOR_CHESTPLATE = register(new ScopindaArmorItem.Chestplate());
	public static final Item SCOPINDA_ARMOR_LEGGINGS = register(new ScopindaArmorItem.Leggings());
	public static final Item SCOPINDA_ARMOR_BOOTS = register(new ScopindaArmorItem.Boots());
	public static final Item BANDI_DUST = register(new BandiDustItem());
	public static final Item BANDI_ORE = register(CopperpackModBlocks.BANDI_ORE, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item BANDI_BLOCK = register(CopperpackModBlocks.BANDI_BLOCK, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item BANDI_PICKAXE = register(new BandiPickaxeItem());
	public static final Item BANDI_AXE = register(new BandiAxeItem());
	public static final Item BANDI_SWORD = register(new BandiSwordItem());
	public static final Item BANDI_SHOVEL = register(new BandiShovelItem());
	public static final Item BANDI_HOE = register(new BandiHoeItem());
	public static final Item BANDI_ARMOR_HELMET = register(new BandiArmorItem.Helmet());
	public static final Item BANDI_ARMOR_CHESTPLATE = register(new BandiArmorItem.Chestplate());
	public static final Item BANDI_ARMOR_LEGGINGS = register(new BandiArmorItem.Leggings());
	public static final Item BANDI_ARMOR_BOOTS = register(new BandiArmorItem.Boots());
	public static final Item WHIST_INGOT = register(new WhistIngotItem());
	public static final Item WHIST_ORE = register(CopperpackModBlocks.WHIST_ORE, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item WHIST_BLOCK = register(CopperpackModBlocks.WHIST_BLOCK, CopperpackModTabs.TAB_COPPER_PACK_BLOCK);
	public static final Item WHIST_PICKAXE = register(new WhistPickaxeItem());
	public static final Item WHIST_AXE = register(new WhistAxeItem());
	public static final Item WHIST_SWORD = register(new WhistSwordItem());
	public static final Item WHIST_SHOVEL = register(new WhistShovelItem());
	public static final Item WHIST_HOE = register(new WhistHoeItem());
	public static final Item WHIST_ARMOR_HELMET = register(new WhistArmorItem.Helmet());
	public static final Item WHIST_ARMOR_CHESTPLATE = register(new WhistArmorItem.Chestplate());
	public static final Item WHIST_ARMOR_LEGGINGS = register(new WhistArmorItem.Leggings());
	public static final Item WHIST_ARMOR_BOOTS = register(new WhistArmorItem.Boots());

	private static Item register(Item item) {
		REGISTRY.add(item);
		return item;
	}

	private static Item register(Block block, CreativeModeTab tab) {
		return register(new BlockItem(block, new Item.Properties().tab(tab)).setRegistryName(block.getRegistryName()));
	}

	@SubscribeEvent
	public static void registerItems(RegistryEvent.Register<Item> event) {
		event.getRegistry().registerAll(REGISTRY.toArray(new Item[0]));
	}
}
